package com.starters.hsge.common.constants

enum class DogAge(val age: String) {
    ONE_MONTH_LESS("1개월 미만"),
    ONE_MONTH("1개월"),
    TWO_MONTHS("2개월"),
    THREE_MONTHS("3개월"),
    FOUR_MONTHS("4개월"),
    FIVE_MONTHS("5개월"),
    SIX_MONTHS("6개월"),
    SEVEN_MONTHS("7개월"),
    EIGHT_MONTHS("8개월"),
    NINE_MONTHS("9개월"),
    TEN_MONTHS("10개월"),
    ELEVEN_MONTHS("11개월"),
    ONE_YEAR("1살"),
    TWO_YEARS("2살"),
    THREE_YEARS("3살"),
    FOUR_YEARS("4살"),
    FIVE_YEARS("5살"),
    SIX_YEARS("6살"),
    SEVEN_YEARS("7살"),
    EIGHT_YEARS("8살"),
    NINE_YEARS("9살"),
    TEN_YEARS("10살"),
    ELEVEN_YEARS("11살"),
    TWELVE_YEARS("12살"),
    THIRTEEN_YEARS("13살"),
    FOURTEEN_YEARS("14살"),
    FIFTEEN_YEARS("15살"),
    SIXTEEN_YEARS("16살"),
    SEVENTEEN_YEARS("17살"),
    EIGHTEEN_YEARS("18살"),
    NINETEEN_YEARS("19살"),
    TWENTY_YEARS("20살"),
    TWENTY_YEARS_MORE("20살 이상")
}